# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 王远谋的博客
email: heywym@qq.com
description: 王远谋的个人博客网站.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: alan_wong
github_username:  alan-w-255

# Build settings
markdown: kramdown
